### PR TITLE
Change 'animation' to 'fiezta'

### PR DESCRIPTION
**Pull request by andresviedma**
An andalusian with no fiezta is not an andalusian.

### CODE REVIEW

**Comment by bameda** [comment]
Si me cambias fiesta por "arrremate" o "jorgorio" te lo acepto

**Comment by bameda** [comment]
http://fititu.es/definicion/cordoba-2/subbetica/carcabuey/arremate-3/

**Comment by bameda** [comment]
Merged manually:  https://github.com/bameda/postcss-andalusian-stylesheets/commit/8ad18b41c9b0cb8fb69160d48eea2693ef541673

**Comment by andresviedma** [comment]
'jorgorio' is good enough  ^_^
(and we have crashed the 'arremate' web, man!) O_O

**Pull request closed without merging**
